import { useEffect, useMemo, useState } from 'react';
import { Bell, Bot, ChartNoAxesCombined, CircleDollarSign, CircleHelp, ClipboardList, Command, ContactRound, Factory, FileText, LayoutDashboard, LockKeyhole, LogOut, Menu, MessageSquare, MoreHorizontal, Plus, ScrollText, Search, ShieldCheck, Sparkles, Users, WalletCards, X } from 'lucide-react';
import { identities, initialEmployees, type Employee, type Role } from './data/mock';
import { Button, Field, IconButton, Modal, Select, Skeleton, Status, Toast } from './components/ui';

type Page = 'home' | 'new-order' | 'orders' | 'customers' | 'forms' | 'messages' | 'production' | 'sales' | 'payroll' | 'analytics' | 'owner-ai' | 'employees' | 'audit' | 'security';
type LoginState = 'normal' | 'loading' | 'invalid' | 'mfa';
const nav = [
  { id: 'home' as Page, label: 'Главная', icon: LayoutDashboard },
  { id: 'new-order' as Page, label: 'Новый заказ', icon: Plus },
  { id: 'orders' as Page, label: 'Заказы', icon: ClipboardList },
  { id: 'customers' as Page, label: 'Клиенты', icon: ContactRound },
  { id: 'forms' as Page, label: 'Бланки', icon: FileText },
  { id: 'messages' as Page, label: 'Сообщения', icon: MessageSquare },
  { id: 'sales' as Page, label: 'Продажи', icon: CircleDollarSign, owner: true },
  { id: 'payroll' as Page, label: 'Зарплаты', icon: WalletCards, owner: true },
  { id: 'analytics' as Page, label: 'Аналитика', icon: ChartNoAxesCombined, owner: true },
  { id: 'owner-ai' as Page, label: 'AI', icon: Bot, owner: true },
  { id: 'production' as Page, label: 'Производство', icon: Factory, owner: true },
  { id: 'employees' as Page, label: 'Сотрудники', icon: Users, owner: true },
  { id: 'audit' as Page, label: 'Журнал действий', icon: ScrollText, owner: true },
  { id: 'security' as Page, label: 'Безопасность', icon: ShieldCheck, owner: true },
];

export function App() {
  const [signedIn, setSignedIn] = useState(false); const [role, setRole] = useState<Role>('SELLER'); const [page, setPage] = useState<Page>('home');
  if (!signedIn) return <Login onSuccess={(r) => { setRole(r); setSignedIn(true); }} />;
  return <Shell role={role} setRole={setRole} page={page} setPage={setPage} logout={() => setSignedIn(false)} />;
}

function Brand() { return <div className="brand"><img src="/planeta-shtor-logo.svg" alt="Планета штор"/><span /><div><b>Planeta AI</b><small>Планета штор</small></div></div>; }
function Login({ onSuccess }: { onSuccess: (role: Role) => void }) {
  const [state, setState] = useState<LoginState>('normal'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [mfa, setMfa] = useState('');
  const submit = () => { if (email.includes('invalid')) return setState('invalid'); if (email.includes('owner')) return setState('mfa'); setState('loading'); setTimeout(() => onSuccess('SELLER'), 800); };
  return <main className="login"><section className="login-card"><Brand /><div className="login-intro"><h1>{state === 'mfa' ? 'Подтвердите вход' : 'Вход в систему'}</h1><p>{state === 'mfa' ? 'Для доступа владельца введите код из приложения-аутентификатора.' : 'Используйте рабочие учётные данные.'}</p></div>
    {state === 'mfa' ? <><Field label="Код подтверждения" error={mfa.length > 0 && mfa.length < 6 ? 'Введите 6 цифр' : undefined}><input autoFocus inputMode="numeric" maxLength={6} placeholder="000 000" value={mfa} onChange={e=>setMfa(e.target.value)}/></Field><Button className="full" onClick={() => mfa === '000000' ? onSuccess('OWNER + SELLER') : setMfa('')}>Подтвердить</Button><Button variant="ghost" className="full" onClick={() => setState('normal')}>Назад ко входу</Button></> : <><Field label="Рабочий email"><input autoFocus placeholder="name@company.by" value={email} onChange={e=>{setEmail(e.target.value); setState('normal')}} /></Field><Field label="Пароль" error={state === 'invalid' ? 'Неверный email или пароль. Попробуйте ещё раз.' : undefined}><input type="password" placeholder="Введите пароль" value={password} onChange={e=>{setPassword(e.target.value); setState('normal')}}/></Field><Button className="full" loading={state === 'loading'} onClick={submit}>Войти</Button><p className="hint">Демо: <code>owner</code> → MFA код <code>000000</code>; <code>invalid</code> → ошибка.</p></>}
  </section><footer>Только для сотрудников «Планеты штор» · <a href="#">Поддержка</a></footer></main>;
}

function Shell({ role, setRole, page, setPage, logout }: { role: Role; setRole: (r:Role)=>void; page:Page; setPage:(p:Page)=>void; logout:()=>void }) {
  const [menu, setMenu] = useState(false); const [mobile, setMobile] = useState(false); const [toast, setToast] = useState(''); const owner = role === 'OWNER + SELLER'; const identity = identities[role];
  useEffect(()=>{ if(toast){const t=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(t)}},[toast]);
  const productionPages: Page[] = ['home', 'orders', 'production', 'messages'];
  const visibleNav = nav.filter(n => role === 'PRODUCTION' ? productionPages.includes(n.id) : !n.owner || owner);
  const current = nav.find(n => n.id === page);
  const crumb = page === 'home' ? 'Рабочее пространство' : ['employees', 'audit', 'security'].includes(page) ? `Администрирование / ${current?.label}` : `Работа / ${current?.label}`;
  return <div className="app"><aside className={mobile ? 'sidebar open' : 'sidebar'}><div className="side-head"><Brand/><IconButton label="Закрыть меню" className="mobile-only" onClick={()=>setMobile(false)}><X size={19}/></IconButton></div><nav>{visibleNav.map(item=>{const I=item.icon; return <button key={item.id} className={page===item.id?'active':''} onClick={()=>{setPage(item.id);setMobile(false)}}><I size={18}/>{item.label}</button>})}</nav><div className="side-bottom"><div className="prototype-switch"><span>PROTOTYPE</span><Select value={role} onChange={v=>{setRole(v as Role);setPage('home')}}><option>SELLER</option><option>OWNER + SELLER</option><option>PRODUCTION</option></Select></div><button className="profile" onClick={()=>setMenu(!menu)}><span className="avatar">{identity.initials}</span><span><b>{identity.name}</b><small>{role}</small></span><MoreHorizontal size={18}/></button>{menu && <div className="profile-menu"><button onClick={()=>setToast('Настройки доступны в следующей фазе')}>Настройки</button><button onClick={logout}><LogOut size={15}/>Выйти</button></div>}</div></aside><div className="mobile-scrim" onClick={()=>setMobile(false)}/><section className="main"><header className="topbar"><IconButton label="Открыть меню" className="mobile-only" onClick={()=>setMobile(true)}><Menu/></IconButton><div className="crumb">{crumb}</div><div className="top-actions"><IconButton label="Помощь"><CircleHelp size={19}/></IconButton><IconButton label="Уведомления"><Bell size={19}/></IconButton></div></header><main className="content">{page==='home' && <Home role={role} onToast={setToast} onNavigate={setPage}/>} {page==='employees' && <Employees onToast={setToast}/>} {page==='security' && <Security onToast={setToast}/>} {page!=='home' && page!=='employees' && page!=='security' && <ComingSoon page={page} role={role} onHome={()=>setPage('home')}/>}</main></section>{toast && <Toast text={toast}/>}</div>;
}

function Home({ role, onToast, onNavigate }: { role:Role; onToast:(s:string)=>void; onNavigate:(p:Page)=>void }) { const owner=role==='OWNER + SELLER'; const production=role==='PRODUCTION'; return <><div className="page-heading"><div><p className="eyebrow">Сегодня, 22 сентября</p><h1>{production?'Рабочая очередь':`Добрый день, ${identities[role].name}`}</h1><p>{production?'Заказы вашего цеха — без коммерческих данных.':'Ваша рабочая зона на сегодня.'}</p></div>{!production && <Button onClick={()=>onNavigate('new-order')}><Plus size={17}/>Новый заказ</Button>}</div>{production ? <ProductionHome onToast={onToast}/> : <><div className="metric-grid"><Metric label="Черновики" value="3" detail="в ваших салонах"/><Metric label="На проверке" value="2" detail="требуют вашего решения"/><Metric label="Подтверждено" value="5" detail="за последние 7 дней"/>{owner && <Metric label="Активные сотрудники" value="4" detail="в компании"/>}</div><section className="panel"><div className="panel-head"><div><h2>Требуют внимания</h2><p>Рабочие действия по вашим салонам</p></div><Button variant="ghost" onClick={()=>onNavigate('orders')}>Все заказы</Button></div><div className="attention"><div className="attention-icon"><Sparkles size={19}/></div><div><b>2 черновика ожидают проверки данных</b><p>Проверьте поля вручную перед подтверждением. AI-подсказки всегда остаются неавторитетными до явного решения.</p></div><Button variant="secondary" onClick={()=>onNavigate('orders')}>Открыть</Button></div></section>{owner && <section className="panel compact"><div className="panel-head"><div><h2>Контроль доступа</h2><p>Владелец видит административные действия в едином интерфейсе.</p></div><Button variant="secondary" onClick={()=>onNavigate('employees')}>Сотрудники</Button></div></section>}</>}</> }
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <article className="metric"><span>{label}</span><b>{value}</b><small>{detail}</small></article>}
function ProductionHome({onToast}:{onToast:(s:string)=>void}){return <><div className="metric-grid"><Metric label="Новые" value="4" detail="к началу работы"/><Metric label="В работе" value="2" detail="в WORKSHOP_MAIN"/><Metric label="Нужна отметка" value="1" detail="изменена ревизия"/></div><section className="panel"><div className="panel-head"><div><h2>Очередь цеха</h2><p>Только производственные сведения</p></div><Status tone="warning">1 изменение</Status></div><div className="production-row"><span className="number">PS-2026-0041</span><span>Комплект штор · 2 позиции</span><span>Срок: 24 сентября</span><Button variant="secondary" onClick={()=>onToast('Статус изменён только в демо-интерфейсе')}>Начать работу</Button></div></section></>}

const placeholderCopy: Partial<Record<Page, string>> = {
  'new-order': 'Здесь будет начинаться создание черновика заказа в разрешённом салоне.',
  orders: 'Здесь появится список заказов в пределах доступных салонов и их текущих состояний.',
  customers: 'Здесь будет доступен предусмотренный OpenSpec поиск клиентов по точному нормализованному телефону.',
  forms: 'Здесь будет UX работы с оригиналами бланков и документами заказа.',
  messages: 'Раздел навигации для будущего сценария сообщений; сам сценарий отложен и пока не реализуется.',
  sales: 'Здесь предусмотрено место для будущего OWNER-представления продаж; метрики и рабочие сценарии пока не реализуются.',
  payroll: 'Зарплаты отложены до отдельного OpenSpec change; расчёты и данные сотрудников в прототип не входят.',
  analytics: 'Аналитика отложена до отдельного OpenSpec change; отчёты и метрики здесь не реализуются.',
  'owner-ai': 'Будущий OWNER AI assistant требует отдельного OpenSpec change. Сейчас показано только место в навигации.',
  production: 'OWNER-представление контроля производства в том же интерфейсе. Очередь и действия здесь пока не реализуются.',
  audit: 'OWNER сможет искать историю по времени, сотруднику, действию, заказу и салону согласно OpenSpec.',
};
function ComingSoon({page,onHome,role}:{page:Page;onHome:()=>void;role:Role}) { const item=nav.find(n=>n.id===page); const Icon=item?.icon ?? FileText; const productionCopy:Partial<Record<Page,string>>={orders:'Здесь появится только производственная проекция подтверждённых заказов без цен, платежей и широких данных клиентов.',production:'Здесь появится очередь WORKSHOP_MAIN со статусами и производственными данными согласно OpenSpec.',messages:placeholderCopy.messages}; const copy=role==='PRODUCTION'?productionCopy[page]:undefined; const deferred=['payroll','analytics','owner-ai'].includes(page); return <><div className="page-heading"><div><p className="eyebrow">{['employees','audit','security','production','sales','payroll','analytics','owner-ai'].includes(page)?'Администрирование':'Рабочее пространство'}</p><h1>{item?.label}</h1><p>Раздел навигации прототипа</p></div></div><section className="panel placeholder-panel"><div className="placeholder-icon"><Icon size={21}/></div><span className="placeholder-kicker">{deferred?'Отложено до отдельного этапа':'Структура согласуется'}</span><h2>{item?.label} появится на своём этапе</h2><p>{copy ?? placeholderCopy[page] ?? 'Это место предусмотрено структурой Planeta AI. Его сценарий сейчас не реализуется.'}</p><Button variant="secondary" onClick={onHome}>Вернуться на главную</Button></section></>; }

function Employees({ onToast }: { onToast:(s:string)=>void }) {
 const [people,setPeople]=useState(initialEmployees); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('Все роли'); const [editing,setEditing]=useState<Employee|null>(null); const [creating,setCreating]=useState(false); const [confirm,setConfirm]=useState<Employee|null>(null);
 const shown=useMemo(()=>people.filter(p=>(filter==='Все роли'||p.role===filter)&&p.name.toLowerCase().includes(query.toLowerCase())),[people,query,filter]);
 const save=(person:Employee)=>{setPeople(all=>all.some(x=>x.id===person.id)?all.map(x=>x.id===person.id?person:x):[...all,person]);setEditing(null);setCreating(false);onToast(person.id.startsWith('new')?'Сотрудник добавлен в демо-список':'Изменения сохранены в демо-режиме')};
 const toggle=(person:Employee)=>{ if(person.role==='OWNER + SELLER'&&person.status==='Активен'&&people.filter(p=>p.role==='OWNER + SELLER'&&p.status==='Активен').length===1){onToast('Нельзя отключить последнего активного OWNER');setConfirm(null);return;} setPeople(ps=>ps.map(p=>p.id===person.id?{...p,status:p.status==='Активен'?'Отключён':'Активен'}:p));setConfirm(null);onToast(person.status==='Активен'?'Сотрудник отключён в демо-режиме':'Сотрудник активирован в демо-режиме')};
 return <><div className="page-heading"><div><p className="eyebrow">Администрирование</p><h1>Сотрудники</h1><p>Управление внутренними учётными записями и доступом.</p></div><Button onClick={()=>setCreating(true)}><Plus size={17}/>Добавить сотрудника</Button></div><section className="panel table-panel"><div className="table-tools"><div className="search"><Search size={17}/><input placeholder="Поиск по имени" value={query} onChange={e=>setQuery(e.target.value)}/></div><Select value={filter} onChange={setFilter}><option>Все роли</option><option>OWNER + SELLER</option><option>SELLER</option><option>PRODUCTION</option></Select></div><div className="table-wrap"><table><thead><tr><th>Сотрудник</th><th>Роль</th><th>Салон / цех</th><th>Статус</th><th aria-label="Действия"/></tr></thead><tbody>{shown.map(p=><tr key={p.id}><td><div className="person"><span className="avatar small">{p.name.split(' ').map(x=>x[0]).join('')}</span><b>{p.name}</b>{p.mfa&&<span className="mfa"><LockKeyhole size={12}/>MFA</span>}</div></td><td><span className="role-pill">{p.role}</span></td><td>{p.place}</td><td><Status tone={p.status==='Активен'?'success':'muted'}>{p.status}</Status></td><td><IconButton label={`Действия для ${p.name}`} onClick={()=>setEditing(p)}><MoreHorizontal size={19}/></IconButton></td></tr>)}</tbody></table></div>{shown.length===0&&<div className="empty"><Users size={25}/><b>Ничего не найдено</b><p>Измените запрос или фильтр.</p></div>}</section>{(editing||creating)&&<EmployeeForm person={editing} onClose={()=>{setEditing(null);setCreating(false)}} onSave={save} onDisable={editing?()=>setConfirm(editing):undefined}/>} {confirm&&<Modal title="Отключить сотрудника?" onClose={()=>setConfirm(null)}><div className="dialog-copy"><p>Сотрудник сразу потеряет доступ к новым защищённым действиям.</p><p className="muted">В prototype это действие меняет только mock data.</p></div><div className="modal-actions"><Button variant="ghost" onClick={()=>setConfirm(null)}>Отмена</Button><Button variant="danger" onClick={()=>toggle(confirm)}>Отключить</Button></div></Modal>}</>;
}
function EmployeeForm({person,onClose,onSave,onDisable}:{person:Employee|null;onClose:()=>void;onSave:(p:Employee)=>void;onDisable?:()=>void}){const [form,setForm]=useState<Employee>(person??{id:`new-${Date.now()}`,name:'',role:'SELLER',place:'SALON_A',status:'Активен'});const [tried,setTried]=useState(false);const update=(key:keyof Employee,value:string)=>setForm({...form,[key]:value} as Employee);const submit=()=>{setTried(true);if(form.name.trim())onSave(form)};return <Modal title={person?'Изменить сотрудника':'Новый сотрудник'} onClose={onClose}><div className="form-grid"><Field label="Имя" error={tried&&!form.name.trim()?'Укажите имя сотрудника':undefined}><input autoFocus value={form.name} onChange={e=>update('name',e.target.value)} placeholder="Например, Seller C"/></Field><Field label="Роль"><Select value={form.role} onChange={v=>update('role',v)}><option>SELLER</option><option>PRODUCTION</option><option>OWNER + SELLER</option></Select></Field><Field label="Салон / цех"><Select value={form.place} onChange={v=>update('place',v)}>{form.role==='PRODUCTION'?<option>WORKSHOP_MAIN</option>:<><option>SALON_A</option><option>SALON_B</option><option>SALON_A · SALON_B</option></>}</Select></Field><Field label="Статус"><Select value={form.status} onChange={v=>update('status',v)}><option>Активен</option><option>Отключён</option></Select></Field></div><p className="form-note">Только OWNER управляет учётными записями. Защита последнего активного OWNER отражена в интерфейсе.</p><div className="modal-actions spread">{onDisable?<Button variant="danger" onClick={onDisable}>Отключить</Button>:<span/>}<div><Button variant="ghost" onClick={onClose}>Отмена</Button><Button onClick={submit}>Сохранить</Button></div></div></Modal>}
function Security({onToast}:{onToast:(s:string)=>void}){const [step,setStep]=useState<'ready'|'verify'|'done'>('ready');return <><div className="page-heading"><div><p className="eyebrow">Администрирование</p><h1>Безопасность</h1><p>Усиленная защита владельца компании.</p></div></div><section className="security-card">{step==='ready'&&<><div className="security-icon"><ShieldCheck size={26}/></div><h2>MFA для OWNER</h2><p>Для всех действий с правами OWNER требуется подтверждённая многофакторная аутентификация. Пароля недостаточно.</p><div className="security-info"><span>Статус</span><Status tone="success">Подключено</Status></div><Button onClick={()=>setStep('verify')}>Проверить MFA</Button></>}{step==='verify'&&<><div className="security-icon"><Command size={26}/></div><h2>Подтвердите код</h2><p>Введите одноразовый код из приложения-аутентификатора.</p><Field label="Код"><input autoFocus inputMode="numeric" placeholder="000 000"/></Field><Button onClick={()=>{setStep('done');onToast('MFA успешно подтверждена')}}>Подтвердить</Button><Button variant="ghost" onClick={()=>setStep('ready')}>Отмена</Button></>}{step==='done'&&<><div className="security-icon good"><ShieldCheck size={26}/></div><h2>Проверка пройдена</h2><p>OWNER-доступ подтверждён для текущей mock-сессии.</p><Button variant="secondary" onClick={()=>setStep('ready')}>Готово</Button></>}</section></>}
